//@ pragma UseQApplication
import Quickshell
import Quickshell.Io
import Quickshell.Services.Notifications
import QtQuick
import "./modules"

ShellRoot {
    id: shellRoot

    Theme { id: theme }
    UiState { id: ui }

    // Wallpaper palette, regenerated by matugen on every wallpaper change
    // (template: ~/.config/quickshell/templates/colors.json, written to
    // ~/.cache/quickshell/colors.json). FileView watches it, so the bar and
    // the rest of the shell recolor live — no restart needed. The property
    // defaults below match Theme.qml, so the shell still looks right if
    // matugen has never run.
    FileView {
        id: wallpaperColors
        path: Quickshell.env("HOME") + "/.cache/quickshell/colors.json"
        watchChanges: true
        onFileChanged: reload()

        JsonAdapter {
            id: wp
            property color bg: "#1b1725"
            property color bgAlt: "#221c30"
            property color card: "#2a2438"
            property color cardHover: "#332c46"
            property color border: "#3a3350"
            property color pill: "#2a2438"
            property color accent: "#ab97f0"
            property color text: "#eae6f7"
            property color subtext: "#9d94b8"
            property color danger: "#f0797a"
        }
    }

    // Live-apply the wallpaper palette (and the UI scale) onto the theme.
    // Everything is gated on config.wallpaperColors, so Settings →
    // "Wallpaper colors" turns the whole wallpaper theming on/off; when it's
    // off the fixed palette in Theme.fixed is used instead. The manual
    // accent color from Settings is honored whenever the accent-from-
    // wallpaper switch is off.
    Binding { target: theme; property: "bg"; value: config.wallpaperColors ? wp.bg : theme.fixed.bg }
    Binding { target: theme; property: "bgAlt"; value: config.wallpaperColors ? wp.bgAlt : theme.fixed.bgAlt }
    Binding { target: theme; property: "card"; value: config.wallpaperColors ? wp.card : theme.fixed.card }
    Binding { target: theme; property: "cardHover"; value: config.wallpaperColors ? wp.cardHover : theme.fixed.cardHover }
    Binding { target: theme; property: "border"; value: config.wallpaperColors ? wp.border : theme.fixed.border }
    Binding { target: theme; property: "pill"; value: config.wallpaperColors ? wp.pill : theme.fixed.pill }
    Binding { target: theme; property: "text"; value: config.wallpaperColors ? wp.text : theme.fixed.text }
    Binding { target: theme; property: "subtext"; value: config.wallpaperColors ? wp.subtext : theme.fixed.subtext }
    Binding { target: theme; property: "danger"; value: config.wallpaperColors ? wp.danger : theme.fixed.danger }
    Binding { target: theme; property: "accent"; value: (config.wallpaperColors && config.accentFromWallpaper) ? wp.accent : config.accentColor }
    Binding { target: theme; property: "scale"; value: config.uiScale }
    Binding { target: theme; property: "gap"; value: Math.round(config.barGap * config.uiScale) }

    // Best-effort detection of the system login picture (SDDM/GDM/
    // AccountsService/lightdm conventions), used as the dashboard profile
    // picture unless the person sets a custom path in Settings.
    Process {
        running: true
        command: ["bash", "-lc",
            "for f in \"$HOME/.face\" \"$HOME/.face.icon\" " +
            "\"/var/lib/AccountsService/icons/$USER\" " +
            "\"/usr/share/sddm/faces/$USER.face.icon\" " +
            "\"/usr/share/sddm/faces/$USER.face\"; do " +
            "[ -f \"$f\" ] && echo \"$f\" && break; done"]
        stdout: StdioCollector {
            onStreamFinished: ui.detectedProfilePath = this.text.trim()
        }
    }

    FileView {
        id: settingsFile
        path: Quickshell.shellDir + "/settings.json"
        watchChanges: true
        onFileChanged: reload()
        onAdapterUpdated: writeAdapter()

        JsonAdapter {
            id: config
            property bool use24h: true
            property bool showSeconds: false
            property bool showWeekday: true
            property string barPosition: "top"
            property real barOpacity: 0.85
            property bool notifSoundEnabled: true
            property bool dndEnabled: false
            property string accentColor: "#ab97f0"
            property bool accentFromWallpaper: true
            property bool wallpaperColors: true
            property int barGap: 8
            property string wallpaperDir: "~/Pictures/Wallpapers"
            property string lastWallpaper: ""
            property string wallpaperTransition: "wipe"
            property real weatherLat: 26.7271
            property real weatherLon: 88.3953
            property string weatherCity: "Siliguri"
            property real uiScale: 1.0
            property string profileImagePath: ""
            property bool barShowLauncher: true
            property bool barShowWorkspaces: true
            property bool barShowMedia: true
            property bool barShowTray: true
            property bool barShowVolume: true
            property bool barShowWifi: true
            property bool barShowBluetooth: true
            property bool barShowNotifications: true
            property bool barShowPower: true
            property bool barShowSettings: true
            property bool showBattery: true
            property bool showIdleInhibitor: true
        }
    }

    NotificationServer {
        id: notifServer
        bodySupported: true
        actionsSupported: true
        imageSupported: true
        persistenceSupported: true
        keepOnReload: true

        onNotification: (notification) => {
            notification.tracked = true;
            if (config.notifSoundEnabled && !config.dndEnabled) soundProc.running = true;
        }
    }

    Process {
        id: soundProc
        running: false
        command: ["paplay", "/usr/share/sounds/freedesktop/stereo/message.oga"]
    }

    Bar {
        theme: theme
        config: config
        ui: ui
        notifServer: notifServer
    }

    Dashboard {
        theme: theme
        config: config
        ui: ui
        osd: osdPopup
    }

    WifiPanel {
        theme: theme
        ui: ui
    }

    AppLauncher {
        theme: theme
        ui: ui
    }

    BluetoothPanel {
        theme: theme
        ui: ui
    }

    PowerMenuPanel {
        theme: theme
        ui: ui
    }

    TrayContextMenu {
        theme: theme
        ui: ui
    }

    NotificationPanel {
        theme: theme
        ui: ui
        notifServer: notifServer
    }

    NotificationToasts {
        theme: theme
        config: config
        notifServer: notifServer
    }

    OsdPopup {
        id: osdPopup
        theme: theme
    }

    SettingsApp {
        theme: theme
        config: config
        ui: ui
    }
}
